# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('quota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=ecommerce.models.catagory_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduce', models.TextField()),
                ('content', models.TextField()),
                ('course_durations', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('minmum_number', models.IntegerField()),
                ('rate', models.IntegerField(default=0)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Catagory')),
            ],
            options={
                'ordering': ('vendor',),
            },
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ecommerce.models.course_media)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Course')),
            ],
            options={
                'ordering': ('course',),
            },
        ),
        migrations.CreateModel(
            name='IndexEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to=ecommerce.models.index_media)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(choices=[('隨機', '隨機'), ('指定分類', '指定分類'), ('特定課程', '特定課程')], max_length=20)),
                ('course', models.ManyToManyField(blank=True, to='ecommerce.Course')),
                ('index_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.IndexEdit')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_number', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.AvailableTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('story', models.TextField()),
                ('catagory', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=ecommerce.models.vendor_logo)),
                ('banner', models.ImageField(upload_to=ecommerce.models.vendor_banner)),
                ('video', models.CharField(max_length=200)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
                ('youtube2', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('剪影', '剪影'), ('故事', '故事')], max_length=50)),
                ('file', models.FileField(upload_to=ecommerce.models.vendor_media)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor')),
            ],
            options={
                'ordering': ('vendor', 'position'),
            },
        ),
        migrations.AddField(
            model_name='ordering',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor'),
        ),
        migrations.AddField(
            model_name='indexrole',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor'),
        ),
        migrations.AddField(
            model_name='course',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor'),
        ),
        migrations.AddField(
            model_name='availabletime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Course'),
        ),
    ]
