# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_vendor_youtube2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='youtube2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
