# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_vendor_youtube2'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('index_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.IndexEdit')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='youtube2',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor'),
        ),
    ]
