# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20170429_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexedit',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='indexedit',
            name='more',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexrole',
            name='more',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexvendor',
            name='more',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
