# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20170429_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexrole',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Catagory'),
        ),
    ]
