# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_indexrole_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexrole',
            name='vendor',
        ),
    ]
