# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_indexrole_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexvendor',
            name='more',
        ),
        migrations.AddField(
            model_name='indexedit',
            name='vendor_more',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
