# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20170430_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletime',
            options={'ordering': ['course']},
        ),
    ]
