# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20170430_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletime',
            options={'ordering': ['course', 'date']},
        ),
    ]
