# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20170430_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='format_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
