# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_availabletime_format_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('不願透露', '不願透露')], max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
        ),
        migrations.AddField(
            model_name='usersubscribe',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor'),
        ),
    ]
