# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_auto_20170501_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
