# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_vendor_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='subscribe',
            new_name='subscribe_number',
        ),
    ]
