# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20170502_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscribe',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
