# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20170502_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscribe',
            name='user_profile',
        ),
    ]
