# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_remove_usersubscribe_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscribe',
            options={'ordering': ['user']},
        ),
    ]
