# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20170502_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Material'),
        ),
    ]
