# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20170505_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='check_value',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordering',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
