# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_remove_ordering_check_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='establish',
            field=models.BooleanField(default=True),
        ),
    ]
