# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_remove_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 6, 9, 31, 5, 410949, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
