# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='banner',
            field=models.ImageField(default=1, upload_to=ecommerce.models.catagory_upload),
            preserve_default=False,
        ),
    ]
