# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_catagory_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='establish',
        ),
        migrations.AddField(
            model_name='ordering',
            name='order_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
