# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0035_auto_20170510_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='quota',
            field=models.PositiveIntegerField(),
        ),
    ]
