# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20170511_1002'),
        ('ecommerce', '0036_auto_20170510_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
            preserve_default=False,
        ),
    ]
