# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_ordering_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='course',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='material',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='participants_number',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='vendor',
        ),
    ]
