# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_auto_20170511_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordering',
            options={'ordering': ['-pk']},
        ),
    ]
