# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_auto_20170511_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='payment_choice',
            field=models.CharField(choices=[('信用卡', '信用卡'), ('超商繳款', '超商繳款')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
