# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_ordering_payment_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='payment_choice',
            field=models.CharField(blank=True, choices=[('信用卡', '信用卡'), ('超商繳款', '超商繳款')], max_length=20),
        ),
    ]
