# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_auto_20170512_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
