# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_catagory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('aply', models.BooleanField(default=False)),
            ],
        ),
    ]
