# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0044_ordering_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('participants_number', models.PositiveIntegerField(default=1)),
                ('voucher', models.CharField(max_length=30)),
                ('total_amount', models.PositiveIntegerField()),
                ('payment_choice', models.CharField(blank=True, choices=[('信用卡', '信用卡'), ('超商繳款', '超商繳款')], max_length=20)),
                ('pay_check', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('available_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.AvailableTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Vendor')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
