# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
