# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-26 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseorder', '0002_auto_20170525_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Voucher'),
        ),
    ]
