# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseorder', '0004_auto_20170528_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorder',
            name='eticket_send',
            field=models.BooleanField(default=False),
        ),
    ]
