# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.FileField(upload_to=index.models.index_media)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='indexbanner',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.IndexPage'),
        ),
    ]
