# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170510_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='participants_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
