# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170510_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='item_totle',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
