# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-18 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_ordering_voucher'),
        ('cart', '0008_remove_cart_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Voucher'),
        ),
    ]
